artifacts_root: artifacts #It will create artifacts folder

data_ingestion:
  root_dir: artifacts/data_ingestion  #It will create this folder
  source_url: https://github.com/entbappy/Branching-tutorial/raw/master/samsumdata.zip
  local_data_file: artifacts/data_ingestion/data.zip  #It will download the data into this folder
  unzip_dir: artifacts/data_ingestion

data_validation:
  root_dir: artifacts/data_validation
  STATUS_FILE: artifacts/data_validation/status.txt
  ALL_REQUIRED_STATUS: ["train","test","validation"]